[versions]
agp = "8.4.0-alpha04"
kotlin = "1.9.0"
tgbotapi = "10.0.0"

[libraries]
tgbotapi = { group = "dev.inmo", name = "tgbotapi", version.ref = "tgbotapi" }

[plugins]
#jetbrains
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }